name: Build for Minecraft 26.1.2

on:
  workflow_dispatch:
    inputs:
      mc_version:
        description: '版本'
        required: true
        default: '26.1.2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update paper-api version in build.gradle.kts
        run: |
          sed -i 's/compileOnly("io.papermc.paper:paper-api:.*"/compileOnly("io.papermc.paper:paper-api:${{ github.event.inputs.mc_version }}-R0.1-SNAPSHOT"/g' build.gradle.kts

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nascraft-${{ github.event.inputs.mc_version }}
          path: build/libs/*.jar
